--<ScriptOptions statementTerminator="!"/>

CREATE TABLE EMPLOYEE090.RESULT_6_1 (
		SALARY DECIMAL(7 , 0)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

GRANT CONTROL ON TABLE EMPLOYEE090.RESULT_6_1 TO USER ITSTUDENTB1!

GRANT ALTER ON TABLE EMPLOYEE090.RESULT_6_1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT DELETE ON TABLE EMPLOYEE090.RESULT_6_1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INDEX ON TABLE EMPLOYEE090.RESULT_6_1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INSERT ON TABLE EMPLOYEE090.RESULT_6_1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT SELECT ON TABLE EMPLOYEE090.RESULT_6_1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE EMPLOYEE090.RESULT_6_1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT UPDATE ON TABLE EMPLOYEE090.RESULT_6_1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

