--<ScriptOptions statementTerminator="!"/>

CREATE SCHEMA UNIVERS090 AUTHORIZATION ITSTUDENTA2!

CREATE TABLE UNIVERS090.BOOK_ADOPTION (
		CNO DECIMAL(4 , 0) NOT NULL,
		SEM DECIMAL(5 , 0),
		BOOK_ISBN DECIMAL(4 , 0) NOT NULL
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE UNIVERS090.COURSE (
		CNO DECIMAL(4 , 0) NOT NULL,
		CNAME CHAR(5),
		DEPT CHAR(5)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE UNIVERS090.ENROLL (
		REGNO DECIMAL(5 , 0) NOT NULL,
		CNO DECIMAL(4 , 0) NOT NULL,
		SEM DECIMAL(1 , 0),
		BOOK_ISBN DECIMAL(4 , 0)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE UNIVERS090.R1 (
		SNAME CHAR(5)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE UNIVERS090.R1STUDENT (
		REGNO DECIMAL(4 , 0) NOT NULL,
		SNAME CHAR(5),
		DEPT CHAR(5),
		MAJOR CHAR(5)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE UNIVERS090.R2 (
		COUNT DECIMAL(1 , 0)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE UNIVERS090.R3 (
		TITLE CHAR(5)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE UNIVERS090.RESULT1 (
		REGNO DECIMAL(4 , 0) NOT NULL,
		SNAME CHAR(5),
		DEPT CHAR(5),
		MAJOR CHAR(5)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE UNIVERS090.STUDENT (
		REGNO DECIMAL(4 , 0) NOT NULL,
		SNAME CHAR(5),
		DEPT CHAR(5),
		MAJOR CHAR(5)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE UNIVERS090.TEXT (
		BOOK_ISBN DECIMAL(4 , 0) NOT NULL,
		TITLE CHAR(5),
		PUBLISH CHAR(5),
		AUTHOR CHAR(5)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE UNIVERS090.R4 (
		REGNO DECIMAL(4 , 0) NOT NULL,
		SNAME CHAR(5),
		DEPT CHAR(5),
		MAJOR CHAR(5)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

ALTER TABLE UNIVERS090.BOOK_ADOPTION ADD CONSTRAINT BOOK_ADOPTION_PK PRIMARY KEY
	(CNO,
	 BOOK_ISBN)!

ALTER TABLE UNIVERS090.COURSE ADD CONSTRAINT COURSE_PK PRIMARY KEY
	(CNO)!

ALTER TABLE UNIVERS090.ENROLL ADD CONSTRAINT ENROLL_PK PRIMARY KEY
	(REGNO,
	 CNO)!

ALTER TABLE UNIVERS090.R1STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY
	(REGNO)!

ALTER TABLE UNIVERS090.RESULT1 ADD CONSTRAINT RESULT1_PK PRIMARY KEY
	(REGNO)!

ALTER TABLE UNIVERS090.STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY
	(REGNO)!

ALTER TABLE UNIVERS090.TEXT ADD CONSTRAINT TEXT_PK PRIMARY KEY
	(BOOK_ISBN)!

ALTER TABLE UNIVERS090.R4 ADD CONSTRAINT STUDENT_PK PRIMARY KEY
	(REGNO)!

ALTER TABLE UNIVERS090.BOOK_ADOPTION ADD CONSTRAINT BOOK_ADOPTION_COURSE_FK FOREIGN KEY
	(CNO)
	REFERENCES UNIVERS090.COURSE
	(CNO)
	ON DELETE CASCADE!

ALTER TABLE UNIVERS090.BOOK_ADOPTION ADD CONSTRAINT BOOK_ADOPTION_TEXT_FK FOREIGN KEY
	(BOOK_ISBN)
	REFERENCES UNIVERS090.TEXT
	(BOOK_ISBN)
	ON DELETE CASCADE!

ALTER TABLE UNIVERS090.ENROLL ADD CONSTRAINT ENROLL_COURSE_FK FOREIGN KEY
	(CNO)
	REFERENCES UNIVERS090.COURSE
	(CNO)
	ON DELETE CASCADE!

ALTER TABLE UNIVERS090.ENROLL ADD CONSTRAINT ENROLL_STUDENT_FK FOREIGN KEY
	(REGNO)
	REFERENCES UNIVERS090.STUDENT
	(REGNO)
	ON DELETE CASCADE!

GRANT ALTERIN ON SCHEMA UNIVERS090 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT CREATEIN ON SCHEMA UNIVERS090 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT DROPIN ON SCHEMA UNIVERS090 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT ALTERIN ON SCHEMA UNIVERS090 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT CREATEIN ON SCHEMA UNIVERS090 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT DROPIN ON SCHEMA UNIVERS090 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTB1!

GRANT ALTER ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTA2!

GRANT ALTER ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.BOOK_ADOPTION TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTB1!

GRANT ALTER ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTA2!

GRANT ALTER ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.COURSE TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTB1!

GRANT ALTER ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTA2!

GRANT ALTER ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.ENROLL TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.R1 TO USER ITSTUDENTB1!

GRANT ALTER ON TABLE UNIVERS090.R1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.R1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.R1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.R1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.R1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.R1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.R1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.R1 TO USER ITSTUDENTA2!

GRANT ALTER ON TABLE UNIVERS090.R1 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.R1 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.R1 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.R1 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.R1 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.R1 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.R1 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.R1STUDENT TO USER ITSTUDENTB1!

GRANT ALTER ON TABLE UNIVERS090.R1STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.R1STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.R1STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.R1STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.R1STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.R1STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.R1STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.R2 TO USER ITSTUDENTB1!

GRANT ALTER ON TABLE UNIVERS090.R2 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.R2 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.R2 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.R2 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.R2 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.R2 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.R2 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.R2 TO USER ITSTUDENTA2!

GRANT ALTER ON TABLE UNIVERS090.R2 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.R2 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.R2 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.R2 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.R2 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.R2 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.R2 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.R3 TO USER ITSTUDENTB1!

GRANT ALTER ON TABLE UNIVERS090.R3 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.R3 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.R3 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.R3 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.R3 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.R3 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.R3 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.R3 TO USER ITSTUDENTA2!

GRANT ALTER ON TABLE UNIVERS090.R3 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.R3 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.R3 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.R3 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.R3 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.R3 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.R3 TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.RESULT1 TO USER ITSTUDENTB1!

GRANT ALTER ON TABLE UNIVERS090.RESULT1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.RESULT1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.RESULT1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.RESULT1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.RESULT1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.RESULT1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.RESULT1 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTB1!

GRANT ALTER ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTA2!

GRANT ALTER ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.STUDENT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTB1!

GRANT ALTER ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTA2!

GRANT ALTER ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.TEXT TO USER ITSTUDENTA2 WITH GRANT OPTION!

GRANT CONTROL ON TABLE UNIVERS090.R4 TO USER ITSTUDENTB1!

GRANT ALTER ON TABLE UNIVERS090.R4 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT DELETE ON TABLE UNIVERS090.R4 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INDEX ON TABLE UNIVERS090.R4 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT INSERT ON TABLE UNIVERS090.R4 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT SELECT ON TABLE UNIVERS090.R4 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT REFERENCES ON TABLE UNIVERS090.R4 TO USER ITSTUDENTB1 WITH GRANT OPTION!

GRANT UPDATE ON TABLE UNIVERS090.R4 TO USER ITSTUDENTB1 WITH GRANT OPTION!

