--<ScriptOptions statementTerminator="!"/>

CREATE SCHEMA EMPLOYEE090 AUTHORIZATION ITSTUDENTB1!

CREATE TABLE EMPLOYEE090.COMPANY (
		COMPANY_NAME CHAR(20) NOT NULL,
		CITY CHAR(10)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE EMPLOYEE090.EMPLOYEE (
		EMPLOYEE_NAME CHAR(20) NOT NULL,
		STREET CHAR(20),
		CITY CHAR(10)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE EMPLOYEE090.MANAGES (
		EMPLOYEE_NAME CHAR(20) NOT NULL,
		MANAGER_NAME CHAR(20)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

CREATE TABLE EMPLOYEE090.WORKS (
		EMPLOYEE_NAME CHAR(20) NOT NULL,
		COMPANY_NAME CHAR(20) NOT NULL,
		SALARY DECIMAL(7 , 0)
	)
	DATA CAPTURE NONE 
	IN USERSPACE1!

ALTER TABLE EMPLOYEE090.COMPANY ADD CONSTRAINT COMPANY_PK PRIMARY KEY
	(COMPANY_NAME)!

ALTER TABLE EMPLOYEE090.EMPLOYEE ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY
	(EMPLOYEE_NAME)!

ALTER TABLE EMPLOYEE090.MANAGES ADD CONSTRAINT MANAGES_PK PRIMARY KEY
	(EMPLOYEE_NAME)!

ALTER TABLE EMPLOYEE090.WORKS ADD CONSTRAINT WORKS_PK PRIMARY KEY
	(EMPLOYEE_NAME,
	 COMPANY_NAME)!

ALTER TABLE EMPLOYEE090.MANAGES ADD CONSTRAINT MANAGES_EMPLOYEE_FK FOREIGN KEY
	(EMPLOYEE_NAME)
	REFERENCES EMPLOYEE090.EMPLOYEE
	(EMPLOYEE_NAME)
	ON DELETE CASCADE!

ALTER TABLE EMPLOYEE090.WORKS ADD CONSTRAINT WORKS_COMPANY_FK FOREIGN KEY
	(COMPANY_NAME)
	REFERENCES EMPLOYEE090.COMPANY
	(COMPANY_NAME)
	ON DELETE CASCADE!

ALTER TABLE EMPLOYEE090.WORKS ADD CONSTRAINT WORKS_EMPLOYEE_FK FOREIGN KEY
	(EMPLOYEE_NAME)
	REFERENCES EMPLOYEE090.EMPLOYEE
	(EMPLOYEE_NAME)
	ON DELETE CASCADE!

